### ISSUE TITLE
Next.js build is crashing with "Error: Web Storage API not found."

### ISSUE THREAD

**Issue by sapkra** [lynoapp/typed-local-store#3]

**Comment by gcascio** [comment]
I added two options to handle SSR scenarios with the 2.0.0 release. One can now suppress the error with `ignoreMissingStorage` which is the preferred solution when SSR does not rely on the `localStorage` being functional (i.e. values can actually be stored and retrieved) which is the common case. To clarify one would normaly check the availability of the `localStorage` to enable SSR:

```typescript
if (typeof window !== 'undefined') {
  localStorage.setItem('my-key', 'my-value')
}
```

By setting `ignoreMissingStorage` to `true` TypedLocalStore mimics this behavior internaly and one can simply write

```typescript
typedLocalStore.setItem('my-key', 'my-value')
```

If one needs the `localStorage` to be functional during SSR a fallback storage can be passed through the `fallbackStorage` option. For convenience this package now ships with the in memory store `MemoryStorage` which mimics the Web Storage API.
